# Training configuration for Shadow Hand MLP Inverse Dynamics Model
# This config consolidates model architecture and training hyperparameters

# Model configuration
model:
  _target_: generative_policies.inverse_dynamics.FlowInverseDynamics
  name: shadow_hand_flow_id
  action_dim: 20
  obs_dim: 157 
  net_arch: [256, 256, 256]
  device: cuda
  checkpoint_path: null  # Set to path to resume from checkpoint

# Training hyperparameters
training:
  # Basic training settings
  num_epochs: 1000
  batch_size: 256
  learning_rate: 0.001  # 1e-3
  device: cuda
  val_split: 0.2
  save_every_n_epochs: 10

  # Regularization
  weight_decay: 0.0001  # 1e-4 (L2 regularization)
  grad_clip: 1.0        # Gradient clipping threshold (0 to disable)

  # Learning rate scheduling
  lr_scheduler: cosine  # Options: cosine, plateau, step, none
  warmup_epochs: 10

  # Early stopping
  early_stopping_patience: 50  # Set to 0 to disable

  # Data processing
  normalize_data: true

  # Performance optimizations
  use_mixed_precision: true  # Enable mixed precision training on GPU

# Data filtering options
data:
  filter_success_only: false  # Only use successful episodes
  min_reward_threshold: null  # Minimum episode reward (null to disable)
